### ISSUE TITLE
Exporting bug on Safari

### ISSUE THREAD

**Issue by incolas** [Gamoloco/known-issues#7]
When exporting a file using Safari, you end up with what seems to be a blank file without an extension.

This is because of a well-documented bug on Safari itself: https://bugs.webkit.org/show_bug.cgi?id=102914. People have been waiting for 3 years for it to get fixed... who knows how much longer will be needed?

In any case, there is a **workaround on the user's side: after you downloaded the file, simply add the .xlsx extension** to it and you will be able to retrieve the data inside.

**Comment by chambo-e** [comment]
The feature was implemented in WebKit (the engine behind Safari) on 31/03/2016 and is currently in testing.
It should land on Safari sooner or later. We'll keep you posted ;)
